name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build Windows x64
              run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

            - name: Build macOS x64
              run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

            - name: Build Linux x64
              run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

            - name: Upload Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: packages
                  path: |
                      bin/Release/netcoreapp3.1/win-x64/publish
                      bin/Release/netcoreapp3.1/osx-x64/publish
                      bin/Release/netcoreapp3.1/linux-x64/publish
