name: Build and Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Subtract 11 from run number
              id: subtract_run_number
              run: echo "::set-output name=result::$(echo "${{ github.run_number }}" - 11 | bc)"
              shell: bash

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 3.1.x

            - name: Install dependencies
              run: dotnet restore

            - name: Build Windows x64
              run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
              working-directory: ${{ github.workspace }}

            - name: Build macOS x64
              run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
              working-directory: ${{ github.workspace }}

            - name: Build Linux x64
              run: dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true
              working-directory: ${{ github.workspace }}

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.subtract_run_number.outputs.result }}
                  release_name: v${{ steps.subtract_run_number.outputs.result }}
                  draft: false
                  prerelease: false

            - name: Upload Windows Executable
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./bin/Release/netcoreapp3.1/win-x64/publish/ThunderStoreModTemplateGenerator.exe
                  asset_name: win-x64.exe
                  asset_content_type: application/octet-stream

            - name: Upload macOS Executable
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./bin/Release/netcoreapp3.1/osx-x64/publish/ThunderStoreModTemplateGenerator
                  asset_name: osx-x64
                  asset_content_type: application/octet-stream

            - name: Upload Linux Executable
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./bin/Release/netcoreapp3.1/linux-x64/publish/ThunderStoreModTemplateGenerator
                  asset_name: linux-x64
                  asset_content_type: application/octet-stream
